---
abstract: 'Dashrep language translator/interpreter'
author:
  - 'Richard Fobes <prog@SolutionsCreative.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Language-Dashrep
provides:
  Language::Dashrep:
    file: lib/Language/Dashrep.pm
    version: 2.32
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 2.32
